#!/bin/sh

case "$1" in
	remove|abort-install|abort-upgrade)
		# This package is being removed, but its configuration has not yet
		# been purged.
		rm -f /boot/overlays/hgltp08.dtbo > /dev/null 2>&1
		rm -f /lib/firmware/hgltp08.txt > /dev/null 2>&1
		;;

	purge)
		rm -f /boot/overlays/hgltp08.dtbo > /dev/null 2>&1
		rm -f /lib/firmware/hgltp08.txt > /dev/null 2>&1
		rm -f /etc/udev/rules.d/99-goodix.rules > /dev/null 2>&1
	        ;;

	disappear)
		;;

	upgrade)
		;;

	failed-upgrade)
		;;

	*) echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;;
esac

exit 0

#DEBHELPER#
