#!/bin/sh

case "$1" in
	install|upgrade|abort-upgrade)
		# Remove all old versions
		rm -f /boot/overlays/hgltp08.dtbo > /dev/null 2>&1
		rm -f /lib/firmware/hgltp08.txt > /dev/null 2>&1
		rm -Rf /var/lib/dkms/hgltp08/*
		dkms remove hgltp08/1.0 --all
		dkms remove hgltp08/1.0.1 --all
		dkms remove hgltp08/1.0.2 --all
		dkms remove hgltp08/1.0.3 --all
		dkms remove hgltp08/1.0.4 --all
		dkms remove hgltp08/1.0.5 --all
		dkms remove hgltp08/1.0.6 --all
		dkms remove hgltp08/1.0.7 --all
		dkms remove hgltp08/1.0.8 --all
		dkms remove hgltp08/1.0.9 --all
		dkms remove hgltp08/1.0.10 --all
		dkms remove hgltp08/1.0.11 --all
		dkms remove hgltp08/1.0.12 --all
		dkms remove hgltp08/1.0.13 --all
		dkms remove hgltp08/1.0.14 --all
		dkms remove hgltp08/1.0.15 --all
		dkms remove hgltp08/1.0.16 --all
		dkms remove hgltp08/1.0.17 --all
		dkms remove hgltp08/1.0.18 --all
		dkms remove hgltp08/1.0.19 --all
		dkms remove hgltp08/1.0.20 --all
		dkms remove hgltp08/1.0.21 --all
		dkms remove hgltp08/1.0.22 --all
		dkms remove hgltp08/1.0.23 --all
		dkms remove hgltp08/1.0.24 --all
		;;
esac

#DEBHELPER#

exit 0
