#!/bin/sh

case "$1" in
	install|upgrade|abort-upgrade)
		# Remove all old versions
		rm -f /boot/overlays/hgltp08.dtbo > /dev/null 2>&1
		dkms remove hgltp08/1.0 --all
		dkms remove hgltp08/1.0.1 --all
		dkms remove hgltp08/1.0.2 --all
		dkms remove hgltp08/1.0.3 --all
		dkms remove hgltp08/1.0.4 --all
		dkms remove hgltp08/1.0.5 --all
		dkms remove hgltp08/1.0.6 --all
		dkms remove hgltp08/1.0.7 --all
		;;
esac

#DEBHELPER#

exit 0
